Dockerfile URL,Command
https://github.com/maxbotmd/MAXBOT-MD/blob/f8c6543d032c6f8dd1264cf53dd8646ccd39f62c/Dockerfile.txt,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
https://github.com/maxbotmd/MAXBOT-MD/blob/f8c6543d032c6f8dd1264cf53dd8646ccd39f62c/Dockerfile.txt,npm install
https://github.com/YogaSakti/imageToSticker/blob/2462288f3b24db368d235c874a14da5e4c228a33/Dockerfile,npm install
https://github.com/YogaSakti/imageToSticker/blob/2462288f3b24db368d235c874a14da5e4c228a33/Dockerfile,npm install --only=dev --ignore-scripts
https://github.com/YogaSakti/imageToSticker/blob/2462288f3b24db368d235c874a14da5e4c228a33/Dockerfile,set -x && apt-get update && apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget --yes --fix-missing && wget --no-check-certificate https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && dpkg -i google-chrome-stable_current_amd64.deb || apt -y -f install && rm google-chrome-stable_current_amd64.deb && apt autoremove --yes
https://github.com/Mrtrier/TRIER_V1/blob/35d9e5af698d225b2a0db19ae17522bfc3716f9e/Dockerfile.txt,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && npm i pm2 -g && rm -rf /var/lib/apt/lists/*
https://github.com/Mrtrier/TRIER_V1/blob/35d9e5af698d225b2a0db19ae17522bfc3716f9e/Dockerfile.txt,git clone https://github.com/franceking1/Flash-Md  /root/𝕋ℝ𝕀𝔼ℝ-𝕍𝟙_BOt
https://github.com/Mrtrier/TRIER_V1/blob/35d9e5af698d225b2a0db19ae17522bfc3716f9e/Dockerfile.txt,npm install pm2 -g
https://github.com/Mrtrier/TRIER_V1/blob/35d9e5af698d225b2a0db19ae17522bfc3716f9e/Dockerfile.txt,npm install --legacy-peer-deps
https://github.com/sgautam2-1/Assignment12/blob/e92f8d7f501cd0907ac86400c8b9933a235f5199/Dockerfile.org,npm install
https://github.com/DEVMOI/RogueIO/blob/9c388050812d24e3e77933daf1c0e9bab8670a75/Dockerfile,npm i -g nodemon
https://github.com/DEVMOI/RogueIO/blob/9c388050812d24e3e77933daf1c0e9bab8670a75/Dockerfile,npm install --quiet
https://github.com/HisokaLabs/hisoka-waweb.js/blob/d826ead1f8538117062903c0401be13f99aa6b2a/Dockerfile,apt-get update && apt-get install -y ffmpeg chromium webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
https://github.com/HisokaLabs/hisoka-waweb.js/blob/d826ead1f8538117062903c0401be13f99aa6b2a/Dockerfile,npm install
https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile,npm i -g pnpm
https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile,mkdir -p /temp/dev
https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile,cd /temp/dev && pnpm install
https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile,pnpm run generate:prisma
https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile,pnpm run build
https://github.com/vhs/SpaceBus/blob/29cd56b417863f29f7ccbf0d8ec39cee2fabf0ae/Dockerfile,yarn install
https://github.com/vhs/SpaceBus/blob/29cd56b417863f29f7ccbf0d8ec39cee2fabf0ae/Dockerfile,yarn build
https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile,rm -rf node_modules
https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile,rm -rf build
https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile,npm install
https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile,npm run build
https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile,npm install --production
https://github.com/cedlerouge/mydocs/blob/28231331341af866772d0f3ebd15bf542ac708b4/Dockerfile,npm install
https://github.com/cedlerouge/mydocs/blob/28231331341af866772d0f3ebd15bf542ac708b4/Dockerfile,npm run build
https://github.com/jarierca/GameVaultFront/blob/6e83b48bb549fb79d4d1d009f037d6e02b40e547/dockerfile,npm cache clean --force
https://github.com/jarierca/GameVaultFront/blob/6e83b48bb549fb79d4d1d009f037d6e02b40e547/dockerfile,npm install
https://github.com/SimDaeSoo/develop-story/blob/fe4a74af41d643d553845f8ba673211fc5ebddff/dockerfile,yarn install && yarn build
https://github.com/SimDaeSoo/develop-story/blob/fe4a74af41d643d553845f8ba673211fc5ebddff/dockerfile,yarn install && yarn build
https://github.com/SimDaeSoo/develop-story/blob/fe4a74af41d643d553845f8ba673211fc5ebddff/dockerfile,apt-get update && apt-get install -y supervisor && apt-get install -y nginx
https://github.com/SimDaeSoo/develop-story/blob/fe4a74af41d643d553845f8ba673211fc5ebddff/dockerfile,chmod +x /develop-story/*.sh
https://github.com/gojnimer-wedding/invitation-frontend/blob/eb9bc4fdf1279e4d8b8e14ad274ec367a660d046/Dockerfile,yarn install --frozen-lockfile
https://github.com/gojnimer-wedding/invitation-frontend/blob/eb9bc4fdf1279e4d8b8e14ad274ec367a660d046/Dockerfile,"if [ ! -f "".env"" ]; then file=$(find . -name "".env*"" | head -n 1); if [ -n ""$file"" ]; then mv ""$file"" .env; fi ;fi"
https://github.com/gojnimer-wedding/invitation-frontend/blob/eb9bc4fdf1279e4d8b8e14ad274ec367a660d046/Dockerfile,yarn build
https://github.com/martibobby/bobbymartin.dev/blob/5c95342c8f68db95fa7646c5817898b256f322c3/Dockerfile,npm i
https://github.com/martibobby/bobbymartin.dev/blob/5c95342c8f68db95fa7646c5817898b256f322c3/Dockerfile,npm run build
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,"echo ""@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}"" > ./.npmrc && npm ci && rm -f ./.npmrc"
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,npx webpack --config webpack.prod.js
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && apt-get -q dist-upgrade -y && apt-get install -y --no-install-recommends libsqlite3-dev && rm -rf /var/lib/apt/lists/*
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,swift package resolve
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,swift build -c release --static-swift-stdlib -Xswiftc -enable-testing
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,"cp ""$(swift build --package-path /build -c release --show-bin-path)/App"" ./"
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,"find -L ""$(swift build --package-path /build -c release --show-bin-path)/"" -regex '.*\.resources$' -exec cp -Ra {} ./ \;"
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,[ -d /build/Public ] && { mv /build/Public ./Public && chmod -R a-w ./Public; } || true
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,[ -d /build/Resources ] && { mv /build/Resources ./Resources && chmod -R a-w ./Resources; } || true
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,[ -d /build/.build ] && { mv /build/.build ./.build && chmod -R a-w ./.build; } || true
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && apt-get -q dist-upgrade -y && apt-get -q install -y ca-certificates tzdata && rm -r /var/lib/apt/lists/*
https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile,useradd --user-group --create-home --system --skel /dev/null --home-dir /app vapor
https://github.com/joheee/NetmanFrontend/blob/b02980e66f6c0747c78b7a38b16074c0d539aeb8/dockerfile,npm install
https://github.com/joheee/NetmanFrontend/blob/b02980e66f6c0747c78b7a38b16074c0d539aeb8/dockerfile,npm run build
https://github.com/Tristan-Muggridge/pafin-code-challenge/blob/3957fa1ffa499035a19cebdb7d020c58151df4f7/dockerfile,npm ci
https://github.com/adr1enbe4udou1n/nestjs-realworld-example-app/blob/82069881bffb1c10627b121d5bc03016ecf3ddae/Dockerfile,apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
https://github.com/jobscale/kabuka/blob/3595232f036316486d9b932365ee183738899dec/Dockerfile,npm i --omit=dev
https://github.com/lucaslopezf/insta-api/blob/eaee51666e0667b279ee9159dab8582e42f0f570/Dockerfile,npm install
https://github.com/lucaslopezf/insta-api/blob/eaee51666e0667b279ee9159dab8582e42f0f570/Dockerfile,npm run build
https://github.com/lucaslopezf/insta-api/blob/eaee51666e0667b279ee9159dab8582e42f0f570/Dockerfile,npm install -g pm2
https://github.com/lizheming/wxhermit/blob/42f9ef17ca1a5b0fd000024fe6463f7082635d69/Dockerfile,npm install --production
https://github.com/jtamminga/jotto_multi/blob/a120505bd868b1bc800cad2014be4d8592e5f917/Dockerfile,yarn set version 4.1.1
https://github.com/jtamminga/jotto_multi/blob/a120505bd868b1bc800cad2014be4d8592e5f917/Dockerfile,yarn install
https://github.com/jtamminga/jotto_multi/blob/a120505bd868b1bc800cad2014be4d8592e5f917/Dockerfile,yarn build
https://github.com/solarwinds/nova/blob/8b204787472ab46c146c6ac3c7f3d3e742956280/Dockerfile,apt-get update && apt-get -y install git curl wget nano vim procps sudo xvfb
https://github.com/solarwinds/nova/blob/8b204787472ab46c146c6ac3c7f3d3e742956280/Dockerfile,"curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo ""deb http://dl.google.com/linux/chrome/deb/ stable main"" > /etc/apt/sources.list.d/google.list && apt-get update && apt-get install -y google-chrome-stable && ln -s /usr/bin/google-chrome /usr/bin/chrome && rm /etc/apt/sources.list.d/google.list"
https://github.com/maswadkar/crm/blob/0ad13d0e27382458d29654363318a732efad61e3/Dockerfile,npm install
https://github.com/halkeye/example-express-websocket/blob/3a1d7ac1d94f517151d09514482fec0a642a6a63/Dockerfile,NODE_ENV=development npm install
https://github.com/halkeye/example-express-websocket/blob/3a1d7ac1d94f517151d09514482fec0a642a6a63/Dockerfile,npm run build
https://github.com/halkeye/example-express-websocket/blob/3a1d7ac1d94f517151d09514482fec0a642a6a63/Dockerfile,npm install
https://github.com/Eren-Nevin/AWS-Change-IP/blob/7d92f5ed4c4528a9779f052c0d4afcf2c1c79462/aws-rotation/Dockerfile,npm install
https://github.com/jobscale/certbot/blob/b31d35f01f2459a5c0915563518db01c3a233c7d/Dockerfile,apt-get update && apt-get install -y --no-install-recommends curl git vim zip unzip tree tmux openssh-client iproute2 dnsutils iputils-ping ncat netcat-openbsd procps bc certbot && rm -fr /var/lib/apt/lists/*
https://github.com/jobscale/certbot/blob/b31d35f01f2459a5c0915563518db01c3a233c7d/Dockerfile,npm i --dev=omit
https://github.com/csprance/next-smrt/blob/9bd5cc2cad5f96d42867c7931b85446695f46979/Dockerfile,mkdir /app
https://github.com/csprance/next-smrt/blob/9bd5cc2cad5f96d42867c7931b85446695f46979/Dockerfile,yarn install
https://github.com/csprance/next-smrt/blob/9bd5cc2cad5f96d42867c7931b85446695f46979/Dockerfile,yarn build
https://github.com/PerwiraKusuma111/hiso/blob/d43d64f36d574d080116ca52fcbb016a0b132fa4/Dockerfile,apt-get update -y && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
https://github.com/PerwiraKusuma111/hiso/blob/d43d64f36d574d080116ca52fcbb016a0b132fa4/Dockerfile,npm install
https://github.com/PerwiraKusuma111/hiso/blob/d43d64f36d574d080116ca52fcbb016a0b132fa4/Dockerfile,npm i -g pm2
https://github.com/PerwiraKusuma111/hiso/blob/d43d64f36d574d080116ca52fcbb016a0b132fa4/Dockerfile,pm2 start index.js
https://github.com/China-bellabe/Shadow-Md/blob/febab3f46dfa29e424eac1d9326385e1b874cb0d/Dockerfile,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && npm i pm2 -g && rm -rf /var/lib/apt/lists/*
https://github.com/China-bellabe/Shadow-Md/blob/febab3f46dfa29e424eac1d9326385e1b874cb0d/Dockerfile,git clone https://github.com/China-bellabe/Shadow-Md  /root/my_app
https://github.com/China-bellabe/Shadow-Md/blob/febab3f46dfa29e424eac1d9326385e1b874cb0d/Dockerfile,npm install pm2 -g
https://github.com/China-bellabe/Shadow-Md/blob/febab3f46dfa29e424eac1d9326385e1b874cb0d/Dockerfile,npm install
https://github.com/thiagodeev/stellar-learning/blob/561230c6bac28da44169597f219931e1c409ab2b/Dockerfile,npm ci --omit=dev && npm cache clean --force
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,apt-get update && apt-get -y install --no-install-recommends apt-utils 2>&1
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,apt-get install -y git procps unzip python3 python3-pip
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,"rm -rf /opt/yarn-* && rm -f /usr/local/bin/yarn && rm -f /usr/local/bin/yarnpkg && apt-get install -y curl apt-transport-https lsb-release && curl -sS https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/pubkey.gpg | apt-key add - 2>/dev/null && echo ""deb https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ stable main"" | tee /etc/apt/sources.list.d/yarn.list && apt-get update && apt-get -y install --no-install-recommends yarn"
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,pip3 install awscli --upgrade
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,chmod +x /usr/local/bin/aws-vault
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,unzip terraform_0.12.3_linux_amd64.zip -d /usr/local/bin/
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,rm -f terraform_0.12.3_linux_amd64.zip
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,npm install -g eslint @aws-amplify/cli apollo-server graphql graphql-cli
https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile,apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
https://github.com/michaelc143/personal-angular-site/blob/9f5d316e3370100137c7ebd2235e17c43faa709c/Dockerfile,npm install -g @angular/cli
https://github.com/michaelc143/personal-angular-site/blob/9f5d316e3370100137c7ebd2235e17c43faa709c/Dockerfile,npm install --force
https://github.com/michaelc143/personal-angular-site/blob/9f5d316e3370100137c7ebd2235e17c43faa709c/Dockerfile,ng build
https://github.com/BOTCAHX/Recode-Hyzer-Md/blob/f245984eb387be7f7eed093755fb85e1938405f6/Dockerfile,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
https://github.com/BOTCAHX/Recode-Hyzer-Md/blob/f245984eb387be7f7eed093755fb85e1938405f6/Dockerfile,npm install && npm install pm2 -g && pm2 link 44ahpi4v79ureap drbnfobrl2hn8hm && pm2 start index.js && pm2 save && pm2 logs && pm2 monit
https://github.com/Helio609/chatgpt-api-nest/blob/58b80061879cdafacda9b52866dcf70727c40c0c/Dockerfile,npm install --production
https://github.com/Helio609/chatgpt-api-nest/blob/58b80061879cdafacda9b52866dcf70727c40c0c/Dockerfile,npm run build
https://github.com/RealOrangeOne/web-rng/blob/72aa499f7d27ab83acc75c36e39ca79c0d1af9be/Dockerfile,npm ci
https://github.com/RealOrangeOne/web-rng/blob/72aa499f7d27ab83acc75c36e39ca79c0d1af9be/Dockerfile,npm run build
https://github.com/ZennoLab/capmonstercloud-docs/blob/08085cbc92bcf6bc4b58893965714716b3d83c66/Dockerfile,npm install
https://github.com/ZennoLab/capmonstercloud-docs/blob/08085cbc92bcf6bc4b58893965714716b3d83c66/Dockerfile,npm run build
https://github.com/delbaze/demo_ci_back/blob/c689c7af3ad5c19f7961713d28ef8c0660a4a786/Dockerfile,mkdir app
https://github.com/delbaze/demo_ci_back/blob/c689c7af3ad5c19f7961713d28ef8c0660a4a786/Dockerfile,npm install
https://github.com/atsarouchas/Movie-List/blob/0d2524e0e186c3b550a6ccb28c5ea1f3531f597c/Dockerfile,npm install
https://github.com/atsarouchas/Movie-List/blob/0d2524e0e186c3b550a6ccb28c5ea1f3531f597c/Dockerfile,npm run build
