[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "build_and_trace_v3"
version = "0.1.0"
description = "A sample Python package"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["build_and_trace*"]