Base Image,Command,Intermediate Dockerfile Command,Dockerfile URL
node:lts,npm i -g @ionic/cli@${IONIC_CLI_VERSION} && ionic --no-interactive config set -g daemon.updates false && ionic --no-interactive config set -g telemetry false,,https://github.com/ionic-team/ionic-cli/blob/fbeac60cdde6f6504900e9c403fa4e79528ca067/Dockerfile
node:lts-bullseye-slim,apt-get update && apt-get install -y --no-install-recommends fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libfreetype6 libgbm1 libharfbuzz0b libnss3 libpango-1.0-0 libx11-6 libxext6 libxkbcommon0 x11-utils xdg-utils zlib1g && rm -rf /var/lib/apt/lists/*,,https://github.com/macbre/phantomas/blob/a37b0a36d80bf1455835878d00111797aeb5934a/Dockerfile
node:lts-bullseye-slim,chown -R nobody:nogroup .,,https://github.com/macbre/phantomas/blob/a37b0a36d80bf1455835878d00111797aeb5934a/Dockerfile
node:lts-bullseye-slim,npm ci,,https://github.com/macbre/phantomas/blob/a37b0a36d80bf1455835878d00111797aeb5934a/Dockerfile
node:lts-bullseye-slim,"echo ""Chrome found in: "" $(find . -wholename '*chrome-linux64/chrome') && ln -s $(find . -wholename '*chrome-linux64/chrome') .",,https://github.com/macbre/phantomas/blob/a37b0a36d80bf1455835878d00111797aeb5934a/Dockerfile
node:lts-bullseye-slim,ldd chrome && chrome --version,,https://github.com/macbre/phantomas/blob/a37b0a36d80bf1455835878d00111797aeb5934a/Dockerfile
node:lts,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/sullyo/prompt2ui/blob/333875ebfc68212e9d55d9ac430c8254dc75b5fd/dockerfile
node:lts,npm run build,"WORKDIR /app
COPY package*.json ./",https://github.com/sullyo/prompt2ui/blob/333875ebfc68212e9d55d9ac430c8254dc75b5fd/dockerfile
node:lts,apt-get update && apt-get install -y python3-pip,,https://github.com/seokyim8/personal_website/blob/02d7d92492feac9161a7f4eac1bf508ae21b791e/DOCKERFILE
node:lts,pip install --upgrade pip --break-system-packages,,https://github.com/seokyim8/personal_website/blob/02d7d92492feac9161a7f4eac1bf508ae21b791e/DOCKERFILE
node:lts,pip install -r ./requirements.txt --break-system-packages,,https://github.com/seokyim8/personal_website/blob/02d7d92492feac9161a7f4eac1bf508ae21b791e/DOCKERFILE
node:lts,npm install,,https://github.com/seokyim8/personal_website/blob/02d7d92492feac9161a7f4eac1bf508ae21b791e/DOCKERFILE
node:lts-iron,npm install,"WORKDIR /gautam_saurav_ui_garden
COPY package*.json ./",https://github.com/sgautam2-1/Assignment12/blob/e92f8d7f501cd0907ac86400c8b9933a235f5199/Dockerfile.org
node:lts-bookworm-slim,chmod +x /tini,ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini,https://github.com/soruly/trace.moe-api/blob/3cee984190381d4f7b15f745f9c398fb1ce63bd8/Dockerfile
node:lts-bookworm-slim,apt-get update && apt-get install -y ffmpeg openjdk-17-jre,ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini,https://github.com/soruly/trace.moe-api/blob/3cee984190381d4f7b15f745f9c398fb1ce63bd8/Dockerfile
node:lts-bookworm-slim,npm install --omit=dev,ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini,https://github.com/soruly/trace.moe-api/blob/3cee984190381d4f7b15f745f9c398fb1ce63bd8/Dockerfile
node:lts,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/joheee/NetmanFrontend/blob/b02980e66f6c0747c78b7a38b16074c0d539aeb8/dockerfile
node:lts,npm run build,"WORKDIR /app
COPY package*.json ./",https://github.com/joheee/NetmanFrontend/blob/b02980e66f6c0747c78b7a38b16074c0d539aeb8/dockerfile
node:lts As production,npm ci,"WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./",https://github.com/PedroH-Santos/api-gerenciador-financeiro/blob/2fd6e4819ed64f8a7548490f39b13d11c794b701/DockerFile
node:lts As production,npm run prisma:generate,"WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./",https://github.com/PedroH-Santos/api-gerenciador-financeiro/blob/2fd6e4819ed64f8a7548490f39b13d11c794b701/DockerFile
node:lts As production,npm run build,"WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./",https://github.com/PedroH-Santos/api-gerenciador-financeiro/blob/2fd6e4819ed64f8a7548490f39b13d11c794b701/DockerFile
node:lts As production,npm ci --only=production && npm cache clean --force,"WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./",https://github.com/PedroH-Santos/api-gerenciador-financeiro/blob/2fd6e4819ed64f8a7548490f39b13d11c794b701/DockerFile
node:lts-buster,addgroup docker --gid=${docker_gid};,,https://github.com/vuejsprojects/nhs-ui/blob/b64f4428773f210c5db1ec98c355198b6aebb53a/image-build/Dockerfile-jenkins
node:lts-buster,apt-get update && apt-get install -y --no-install-recommends build-essential && apt-get install -y --no-install-recommends git,,https://github.com/vuejsprojects/nhs-ui/blob/b64f4428773f210c5db1ec98c355198b6aebb53a/image-build/Dockerfile-jenkins
node:lts-buster,"apt-get update && apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common && curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo ""$ID"")/gpg > /tmp/dkey; apt-key add /tmp/dkey && add-apt-repository ""deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo ""$ID"") $(lsb_release -cs) stable"" && apt-get update && apt-get -y install docker-ce && groupadd -g ${gid} ${group}  && useradd -M -u ${uid} -g ${gid} ${user} && usermod -aG docker jenkins",,https://github.com/vuejsprojects/nhs-ui/blob/b64f4428773f210c5db1ec98c355198b6aebb53a/image-build/Dockerfile-jenkins
node:lts-buster,yarn,"WORKDIR /usr/src/app
COPY . .",https://github.com/crybapp/api/blob/39dd345ae808c6a25f9f49b8f7085371ab494327/Dockerfile
node:lts-buster,yarn build,"WORKDIR /usr/src/app
COPY . .",https://github.com/crybapp/api/blob/39dd345ae808c6a25f9f49b8f7085371ab494327/Dockerfile
ubuntu:22.04 AS linux,"set -ex && apt-get update --fix-missing && apt-get install -qy --no-install-recommends ca-certificates tzdata locales procps net-tools file ocl-icd-libopencl1 clinfo && apt-get clean && rm -rf /var/lib/apt/lists/* && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 && echo ""$TZ"" > /etc/timezone",,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,set -ex && apt-get update --fix-missing && apt-get install -qy --no-install-recommends unzip sudo ocl-icd-opencl-dev,,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,make get-libs,,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,"--mount=type=secret,id=mynetrc,dst=/root/.netrc go mod download",,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,"--mount=type=cache,id=build,target=/root/.cache/go-build make build VERSION=${VERSION}",,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,"--mount=type=cache,id=build,target=/root/.cache/go-build make gen-p2p-identity",,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04 AS linux,"--mount=type=cache,id=build,target=/root/.cache/go-build make merge-nodes VERSION=${VERSION}",,https://github.com/spacemeshos/go-spacemesh/blob/3adf465d182f4d5c7291be8b2f85b79a07883ccf/Dockerfile
ubuntu:22.04,apt-get update,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,apt-get install -y ca-certificates curl gnupg,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,install -m 0755 -d /etc/apt/keyrings,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,chmod a+r /etc/apt/keyrings/docker.gpg,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,"echo ""deb [arch=""$(dpkg --print-architecture)"" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ""$(. /etc/os-release && echo ""$VERSION_CODENAME"")"" stable"" | tee /etc/apt/sources.list.d/docker.list > /dev/null",,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,apt-get update,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin,,https://github.com/piyh/gitlab_docker_compose/blob/0fdb907c2e1a2aaf97830dc7ed430439473d299e/dockerfile
ubuntu:22.04,wget -P /usr/src/ https://github.com/ndducnha/pqc_socrates/raw/main/server.py && wget -P /usr/src/ https://github.com/ndducnha/pqc_socrates/raw/main/client.py,,https://github.com/ndducnha/pqc_socrates/blob/7ef21ccb6ce1e04a62f105d2e2cbf4338eafcf72/Dockerfile.txt
ubuntu:22.04,apt-get update && apt-get install -y tar wget bash rsync gcc libfreetype6-dev libhdf5-serial-dev libpng-dev libzmq3-dev unzip pkg-config software-properties-common graphviz git curl libgeos++-dev proj-data proj-bin libgeos-dev nodejs npm build-essential gcc python3-dev libffi-dev libssl-dev python3-pip openssh-server openssh-client tk -y,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,tar -xf Python-${PYTHON_VERSION}.tgz,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,cd ./Python-${PYTHON_VERSION} && ./configure --prefix=/usr/local/python${PYTHON_VERSION} --enable-loadable-sqlite-extensions --enable-shared && make install,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,apt-get install -y openjdk-8-jdk && apt-get install -y ant && apt-get clean;,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,apt-get install ca-certificates-java && apt-get clean && update-ca-certificates -f;,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,export JAVA_HOME,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,"echo ""export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/"" >> ~/.bashrc",,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,pip3 install --upgrade pip,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,pip install jupyterlab notebook,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,wget ${url},,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,cat requirements.txt | xargs -n 1 pip install,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,jupyter lab build,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,jupyter labextension install @jupyter-widgets/jupyterlab-manager,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,rm -rf requirements.txt,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,pip install jupyter_contrib_nbextensions,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,jupyter contrib nbextension install --sys-prefix,,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,groupadd -g ${gid} ${group},,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,useradd -u ${uid} -g ${group} -s /bin/sh -m ${user},,https://github.com/Chrisebell24/setup/blob/2ee5c31fa4cf1c58e60021ec56f59d5e54a40d98/DockerFile
ubuntu:22.04,/opt/src/scripts/build_container.sh,COPY build_container.sh /opt/src/scripts/build_container.sh,https://github.com/rust-vmm/rust-vmm-container/blob/9a237cd29cf7dac1f29512273bb24d3473271638/Dockerfile
ubuntu:22.04,apt update && apt install -y build-essential && apt install -y libnet-ldap-perl && apt install -y libpcre2-dev && apt install -y libc-ares-dev && apt install -y checkinstall && ./configure && make && checkinstall --install=no --default --pkgname=tac-plus-ng --pkgversion=1 && cp tac-plus-ng_*.deb /tac-plus-ng.deb,"COPY event-driven-servers/ /opt/tac_plus-ng
WORKDIR /opt/tac_plus-ng",https://github.com/DubrovskyEI/tac_plus-ng-k8s/blob/43c82fa11e51561643fd7bd4ed40dbbb7497a87a/Dockerfile.md
ubuntu:22.04,apt update && apt install -y libnet-ldap-perl && apt install -y libpcre2-dev && apt install -y libc-ares-dev && dpkg -i /tac-plus-ng.deb && rm /tac-plus-ng.deb,"COPY event-driven-servers/ /opt/tac_plus-ng
WORKDIR /opt/tac_plus-ng",https://github.com/DubrovskyEI/tac_plus-ng-k8s/blob/43c82fa11e51561643fd7bd4ed40dbbb7497a87a/Dockerfile.md
ubuntu:22.04,apt-get update && apt-get install -y --no-install-recommends python3-pip python3-dev libpq-dev curl git build-essential default-libmysqlclient-dev libssl-dev libffi-dev locales && apt-get clean && rm -rf /var/lib/apt/lists/*,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,mkdir -p $AIRFLOW_HOME/dags $AIRFLOW_HOME/logs $AIRFLOW_HOME/plugins $AIRFLOW_HOME/dags/src $AIRFLOW_HOME/dags/data,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,pip3 install --no-cache-dir apache-airflow flask pendulum pyarrow pydantic flask-session pandas scikit-learn,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,pip3 install --no-cache-dir -r /requirements.txt,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,chmod +x $AIRFLOW_HOME/shell_files/*.sh,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,$AIRFLOW_HOME/shell_files/run_airflow_db_init.sh,,https://github.com/ArjunSridharkumar/complete_ml_pipeline/blob/3e0dbc0c34784e9cb5b20866883112deaf63f30f/dockerfile.txt
ubuntu:22.04,apt update && apt-get install -y git subversion make vim mc python3 python3-venv python3-pip flex gawk zip bison ffmpeg libsm6 libxext6 libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6 xvfb x11-apps,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,useradd -ms /bin/bash Jenkins,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,python3 -m venv /home/Jenkins/venv,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,chown -R Jenkins: /home/Jenkins/venv,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,. venv/bin/activate && pip3 install --upgrade pip,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,. venv/bin/activate && pip3 install --no-cache-dir -r requirements.txt,,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,"sed -i 's|path: \\""./video.mp4\\""|path: \\""0\\""|' config.yaml",,https://github.com/GachiSlave/sofg_eng/blob/ab23a16e4c3e92815c95896c5c3dbe17abadce72/Dockerfile-1.txt
ubuntu:22.04,apt-get update && apt-get install -y --no-install-recommends software-properties-common gnupg wget lsb-release ca-certificates git build-essential autotools-dev automake libtool libtiff-dev zlib1g-dev libjpeg-dev libpng-dev libleptonica-dev libjbig2dec0-dev && rm -rf /var/lib/apt/lists/*,,https://github.com/Artyum/OCR-Container/blob/65251dd82d026998320fec135154132374f6ea1d/dockerfile
ubuntu:22.04,add-apt-repository ppa:alex-p/tesseract-ocr-devel && apt-get update && apt-get install -y --no-install-recommends tesseract-ocr tesseract-ocr-all ocrmypdf poppler-utils pdftk unpaper inotify-tools pngquant python3 python3-pip && rm -rf /var/lib/apt/lists/*,,https://github.com/Artyum/OCR-Container/blob/65251dd82d026998320fec135154132374f6ea1d/dockerfile
ubuntu:22.04,git clone https://github.com/agl/jbig2enc.git /tmp/jbig2enc && cd /tmp/jbig2enc && ./autogen.sh && ./configure && make && make install && rm -rf /tmp/jbig2enc,,https://github.com/Artyum/OCR-Container/blob/65251dd82d026998320fec135154132374f6ea1d/dockerfile
ubuntu:22.04,git clone https://github.com/tesseract-ocr/tessdata.git && mv -f tessdata/*traineddata /usr/share/tesseract-ocr/5/tessdata/ && mv -f tessdata/script /usr/share/tesseract-ocr/5/tessdata/ && rm -rf tessdata,,https://github.com/Artyum/OCR-Container/blob/65251dd82d026998320fec135154132374f6ea1d/dockerfile
ubuntu:22.04,pip3 install --no-cache-dir --upgrade pip && pip3 install --no-cache-dir watchdog img2pdf,,https://github.com/Artyum/OCR-Container/blob/65251dd82d026998320fec135154132374f6ea1d/dockerfile
