Base Image,Command,Intermediate Dockerfile Command,Dockerfile URL
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/maxbotmd/MAXBOT-MD/blob/f8c6543d032c6f8dd1264cf53dd8646ccd39f62c/Dockerfile.txt
node:lts,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/YogaSakti/imageToSticker/blob/2462288f3b24db368d235c874a14da5e4c228a33/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && npm i pm2 -g && rm -rf /var/lib/apt/lists/*,,https://github.com/Mrtrier/TRIER_V1/blob/35d9e5af698d225b2a0db19ae17522bfc3716f9e/Dockerfile.txt
node:lts-iron,npm install,"WORKDIR /gautam_saurav_ui_garden
COPY package*.json ./",https://github.com/sgautam2-1/Assignment12/blob/e92f8d7f501cd0907ac86400c8b9933a235f5199/Dockerfile.org
node:lts,npm i -g nodemon,WORKDIR /usr/src/app,https://github.com/DEVMOI/RogueIO/blob/9c388050812d24e3e77933daf1c0e9bab8670a75/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg chromium webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/HisokaLabs/hisoka-waweb.js/blob/d826ead1f8538117062903c0401be13f99aa6b2a/Dockerfile
node:lts as base,npm i -g pnpm,WORKDIR /usr/src/app,https://github.com/TungLe0319/DontTrustSkinnyCooks/blob/47cd826b88f3d5529e90e024d8723be159ccbfcd/dockerfile
node:lts as build,yarn install,"WORKDIR /app
COPY package.json ./
COPY yarn.lock ./",https://github.com/vhs/SpaceBus/blob/29cd56b417863f29f7ccbf0d8ec39cee2fabf0ae/Dockerfile
node:lts-slim as run,rm -rf node_modules,"WORKDIR /app
COPY package*.json ./",https://github.com/Whynot830/whynotpc-svelte/blob/1f35adb8229fabba8822a4f26446d9556a85bd4d/dockerfile
node:lts as base,npm install,"WORKDIR /home/node/app
COPY --chown=node:node ./mydocs/ /home/node/app/
WORKDIR /home/node/app",https://github.com/cedlerouge/mydocs/blob/28231331341af866772d0f3ebd15bf542ac708b4/Dockerfile
node:lts,npm cache clean --force,"WORKDIR /app
COPY package.json ./",https://github.com/jarierca/GameVaultFront/blob/6e83b48bb549fb79d4d1d009f037d6e02b40e547/dockerfile
node:lts,yarn install && yarn build,"COPY    nextjs  /develop-story/nextjs/
WORKDIR /develop-story/nextjs/",https://github.com/SimDaeSoo/develop-story/blob/fe4a74af41d643d553845f8ba673211fc5ebddff/dockerfile
node:lts AS runtime,yarn install --frozen-lockfile,"WORKDIR /app
COPY package.json yarn.lock ./",https://github.com/gojnimer-wedding/invitation-frontend/blob/eb9bc4fdf1279e4d8b8e14ad274ec367a660d046/Dockerfile
node:lts AS build,npm i,"WORKDIR /app
COPY . .",https://github.com/martibobby/bobbymartin.dev/blob/5c95342c8f68db95fa7646c5817898b256f322c3/Dockerfile
node:lts-slim as node,"echo ""@fortawesome:registry=https://npm.fontawesome.com/\\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}"" > ./.npmrc && npm ci && rm -f ./.npmrc","WORKDIR /build
COPY package*.json ./",https://github.com/SwiftFiddle/swiftregex/blob/4e2bdd7df721d52a129af5e5b257d725a689c2ff/Dockerfile
node:lts as builder,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/joheee/NetmanFrontend/blob/b02980e66f6c0747c78b7a38b16074c0d539aeb8/dockerfile
node:lts,npm ci,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/Tristan-Muggridge/pafin-code-challenge/blob/3957fa1ffa499035a19cebdb7d020c58151df4f7/dockerfile
node:lts-slim,apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*,,https://github.com/adr1enbe4udou1n/nestjs-realworld-example-app/blob/82069881bffb1c10627b121d5bc03016ecf3ddae/Dockerfile
node:lts-bullseye-slim,npm i --omit=dev,"WORKDIR /home/node
COPY --chown=node:staff package.json .",https://github.com/jobscale/kabuka/blob/3595232f036316486d9b932365ee183738899dec/Dockerfile
node:lts AS builder,npm install,"WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src ./src",https://github.com/lucaslopezf/insta-api/blob/eaee51666e0667b279ee9159dab8582e42f0f570/Dockerfile
node:lts-buster-slim,npm install --production,"WORKDIR /app
COPY package.json production.js /app/
COPY view /app/view
COPY src /app/src",https://github.com/lizheming/wxhermit/blob/42f9ef17ca1a5b0fd000024fe6463f7082635d69/Dockerfile
node:lts-bullseye-slim,yarn set version 4.1.1,"WORKDIR /usr/src/app
COPY . .",https://github.com/jtamminga/jotto_multi/blob/a120505bd868b1bc800cad2014be4d8592e5f917/Dockerfile
node:lts-slim,apt-get update && apt-get -y install git curl wget nano vim procps sudo xvfb,,https://github.com/solarwinds/nova/blob/8b204787472ab46c146c6ac3c7f3d3e742956280/Dockerfile
node:lts-slim,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/maswadkar/crm/blob/0ad13d0e27382458d29654363318a732efad61e3/Dockerfile
node:lts,NODE_ENV=development npm install,COPY package.json package-lock.json ./,https://github.com/halkeye/example-express-websocket/blob/3a1d7ac1d94f517151d09514482fec0a642a6a63/Dockerfile
node:lts-buster,npm install,"COPY . /app/
WORKDIR /app",https://github.com/Eren-Nevin/AWS-Change-IP/blob/7d92f5ed4c4528a9779f052c0d4afcf2c1c79462/aws-rotation/Dockerfile
node:lts-bookworm-slim,apt-get update && apt-get install -y --no-install-recommends curl git vim zip unzip tree tmux openssh-client iproute2 dnsutils iputils-ping ncat netcat-openbsd procps bc certbot && rm -fr /var/lib/apt/lists/*,WORKDIR /root,https://github.com/jobscale/certbot/blob/b31d35f01f2459a5c0915563518db01c3a233c7d/Dockerfile
node:lts,mkdir /app,,https://github.com/csprance/next-smrt/blob/9bd5cc2cad5f96d42867c7931b85446695f46979/Dockerfile
node:lts-buster,apt-get update -y && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/PerwiraKusuma111/hiso/blob/d43d64f36d574d080116ca52fcbb016a0b132fa4/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && npm i pm2 -g && rm -rf /var/lib/apt/lists/*,,https://github.com/China-bellabe/Shadow-Md/blob/febab3f46dfa29e424eac1d9326385e1b874cb0d/Dockerfile
node:lts-hydrogen,npm ci --omit=dev && npm cache clean --force,"WORKDIR /app
COPY package.json package-lock.json ./",https://github.com/thiagodeev/stellar-learning/blob/561230c6bac28da44169597f219931e1c409ab2b/Dockerfile
node:lts,apt-get update && apt-get -y install --no-install-recommends apt-utils 2>&1,,https://github.com/blastmotion/docker-tools-devops/blob/f1d926c263cff0d9fe2ebad9ee900ae38b134349/Dockerfile
node:lts,npm install -g @angular/cli,WORKDIR /app,https://github.com/michaelc143/personal-angular-site/blob/9f5d316e3370100137c7ebd2235e17c43faa709c/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/BOTCAHX/Recode-Hyzer-Md/blob/f245984eb387be7f7eed093755fb85e1938405f6/Dockerfile
node:lts,npm install --production,"WORKDIR /app
COPY ./package.json /app",https://github.com/Helio609/chatgpt-api-nest/blob/58b80061879cdafacda9b52866dcf70727c40c0c/Dockerfile
node:lts-slim as build,npm ci,"WORKDIR /app
COPY ./package.json ./package-lock.json ./",https://github.com/RealOrangeOne/web-rng/blob/72aa499f7d27ab83acc75c36e39ca79c0d1af9be/Dockerfile
node:lts as base,npm install,"WORKDIR /home/node/app
COPY --chown=node:node . /home/node/app/
WORKDIR /home/node/app",https://github.com/ZennoLab/capmonstercloud-docs/blob/08085cbc92bcf6bc4b58893965714716b3d83c66/Dockerfile
node:lts,mkdir app,,https://github.com/delbaze/demo_ci_back/blob/c689c7af3ad5c19f7961713d28ef8c0660a4a786/Dockerfile
node:lts,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/atsarouchas/Movie-List/blob/0d2524e0e186c3b550a6ccb28c5ea1f3531f597c/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/DGDEEPAK/Zenitsu-Bot2/blob/fd5d798b27f0b546c78345ba052645ac740001d5/Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*,,https://github.com/Qhingthuth/Zenitsu-Bot2./blob/fd5d798b27f0b546c78345ba052645ac740001d5/Dockerfile
node:lts,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/dandyproject/gabungan/blob/e2624752db1e39a49f32bd30d15b32228be38d34/Dockerfile
node:lts,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/Kresswell/Cc-checker/blob/95f7ab6b5e120b33b7d4c7ba1a4ca5b1c6a23eca/Dockerfile
node:lts,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/MFarelS/imageToSticker/blob/8932dfb8ac950aeef74f0f76bfc53fc0bdf70af1/Dockerfile
node:lts,npm install,"WORKDIR /usr/src/app
COPY package*.json ./",https://github.com/MarcosRamosGit/BotWpp/blob/38c2353e76823a3bb98f996575422f3a4489746e/Dockerfile
node:lts-bullseye-slim,npm i --omit=dev,"WORKDIR /home/node
COPY --chown=node:staff package.json .",https://github.com/jobscale/speedtest/blob/e95f6f2eb65f115bf897f31f6080394d1f62f673/Dockerfile
node:lts-bullseye-slim,npm i --omit=dev,"WORKDIR /home/node
COPY --chown=node:staff package.json .",https://github.com/jobscale/news-top/blob/fa699c3904f05a64da4d074726369f155d69ffff/Dockerfile
node:lts-bullseye-slim,npm i --omit=dev,"WORKDIR /home/node
COPY --chown=node:staff package.json .",https://github.com/jobscale/info-certificate/blob/6ad08f73b560c422e14855e2160899f165f758bd/Dockerfile
node:lts,NODE_ENV=development npm install,COPY package.json package-lock.json ./,https://github.com/halkeye/example-express-stream/blob/bf9d2215e3b8f48fa8e4c20ce921f618c5278909/Dockerfile
node:lts,npm install -g eslint prettier,,https://github.com/webpack/webpack-cli/blob/ea0d9b12522955dc9a046411be244262eb5103bd/.devcontainer/Dockerfile
node:lts AS build,"wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo ""deb http://dl.google.com/linux/chrome/deb/ stable main"" > /etc/apt/sources.list.d/google-chrome.list && apt-get update && apt-get -y install google-chrome-stable","WORKDIR /app
COPY . /app",https://github.com/devonfw/my-thai-star/blob/a0a62bee0b5c14bba583c49654b31a67774a7067/angular/Dockerfile.travis
node:lts as build,corepack enable,"WORKDIR /usr/src/app
COPY package.json yarn.lock .yarnrc.yml ./
COPY packages/simpleserialize.com/package.json packages/simpleserialize.com/yarn.lock packages/simpleserialize.com/",https://github.com/ChainSafe/ssz/blob/67bcd881cae2771837232479a68f807813b703e9/simpleserialize.Dockerfile
node:lts-slim,apt-get update && apt-get install -y chromium && npm install -g pnpm && pnpm install,ADD package.json pnpm-lock.yaml /,https://github.com/GeopJr/CO2/blob/5d41ab048a15abfe7a429f9d7a0c55547361d1ac/Dockerfile.base
node:lts-slim,mkdir /app,,https://github.com/Aurora-Admin-Panel/frontend/blob/7c8bcde889dda8a7e86e41497f64525471da3ee1/Dockerfile-dev
node:lts,cd /work && npm install && npm run build:full && cp -rf build /app,"COPY [ ""./"", ""/work/"" ]",https://github.com/jc-lab/ultravnc_repeater.js/blob/090945525480073481d1e60084b425800fad9798/app.Dockerfile
node:lts,cd ../../shared && npm install && cd ../microservices/videostreaming,"WORKDIR /home/microservices/videostreaming
COPY shared ../../shared
COPY microservices/videostreaming ./",https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g41/blob/c67878188bbd93385a89406c08145fae0aa102bd/backend/microservices/videostreaming/Dockerfile.dev
node:lts as frontend-builder,corepack enable pnpm,WORKDIR /usr/src/app,https://github.com/COSCUP/conf-ops/blob/ceeb25c3083fd433c0ac3080f6444cffa3eb5b0d/Dockerfile
node:lts,npm clean-install,"WORKDIR /source
COPY NodeApp/package.json ./NodeApp/
COPY NodeApp/package-lock.json ./NodeApp/
WORKDIR /source/NodeApp",https://github.com/oliversturm/hosteurope-docker-tutorial-1/blob/7e4299f62f5ceb2f2fdbff1cd00ee5fe4e3b1720/NodeApp.Dockerfile
node:lts AS stage-build,yarn global add jest,"WORKDIR /usr/src
COPY packages-client/client/package.json packages-client/client/yarn.lock packages-client/client/tsconfig.json ./",https://github.com/bear-in-a-box/team-app/blob/db7a70da3a777076126f812e9898834176afaf1f/client.Dockerfile
node:lts,npm install --prefer-offline --frozen-lockfile --non-interactive --production=false,"WORKDIR /app
COPY . .",https://github.com/Nitwel/nitwel.de/blob/d9e808a367bc4fa22471ded2d1cd9055187e90ce/Dockerfile
node:lts as builder,npm install,"WORKDIR /app
COPY package.json package-lock.json ./",https://github.com/samuelloza/citc2024-taller-front/blob/f3cfe4b56c723ada0f9f7c6d8ecb6eecde4987c2/Dockerfile
node:lts as builder,npm ci,"WORKDIR /app
COPY . .",https://github.com/terra-money/fcd-classic/blob/20218bfa9292405f667ff02a3c4daa11d420897c/Dockerfile
node:lts-hydrogen,npm install,"WORKDIR /app
COPY [""package.json"", ""package-lock.json*"", ""./""]",https://github.com/fawzanrizqy/mockup-IMDB-mobile/blob/a5676d3a746c8f5ef4a5e8c3900c717b3da05484/server/services/app/Dockerfile
node:lts-slim,npm install -g http-server vite,,https://github.com/lebrunthibault/protocol0/blob/0695f72beeb1a7e4d687e093d25260347f621606/p0_web/frontend/development.Dockerfile
node:lts,npm install,"WORKDIR /app
ADD . /app",https://github.com/Loopring/protocols/blob/425d152e5dee56d847335481ac5da56eba9f31da/packages/hebao_v1/Dockerfile-test
node:lts-slim AS cvat-ui,"yarn config set ""strict-ssl"" false -g","COPY package.json /tmp/
COPY yarn.lock /tmp/
COPY cvat-core/package.json /tmp/cvat-core/
COPY cvat-canvas/package.json /tmp/cvat-canvas/
COPY cvat-canvas3d/package.json /tmp/cvat-canvas3d/
COPY cvat-ui/package.json /tmp/cvat-ui/
COPY cvat-data/package.json /tmp/cvat-data/
WORKDIR /tmp/",https://github.com/blossom-agit/docker/blob/5abac87e1e79cfc824dafec2e0fa0fe60dcd1ba7/cvat/Dockerfile.ui
node:lts,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/achrafainhajar/42-Transcendence/blob/e03fd9f75063b140ae73a0e408bac51b310acb4c/backend/Dockerfile.dev
node:lts-hydrogen,npm install,"WORKDIR /app
COPY . .",https://github.com/SafouaneM/portfolio-hackathon/blob/81c06f61bae61015b16616914b72d800bca8cb1a/Dockerfile
node:lts-slim AS npmbuild,apt-get update && apt-get install -y libgdiplus,,https://github.com/GensouSakuya/qqguild-live-chat/blob/967dbd858391c64f41b6bd9ee19f1e8d97b0515f/src/qqguildlivechat/Dockerfile
node:lts,npm install,"WORKDIR /var/www/html/app/frontend
COPY . .",https://github.com/jpabloglez/docker-django-drf-vue-vite/blob/9f60c5f0ce3e47a618b4ce4fd87b06f52966aa43/dockerfiles/Dockerfile.frontend
--platform=$BUILDPLATFORM node:lts-slim AS static_assets_build,apt-get update -q && apt-get install --no-install-recommends -y git libsqlite3-dev libc6-dev libevent-dev libgmp-dev libpcre2-dev libpng-dev libssl-dev libyaml-dev zlib1g-dev,WORKDIR /khodo,https://github.com/kwalter94/khodo/blob/c10f6aec04c8b276bfe707dfbca98fc5ce6cd395/docker/Dockerfile
node:lts-gallium,apt update && apt install nano -y,"WORKDIR /app
COPY . /app",https://github.com/mwbowo/cix/blob/e37462d572432e1d125cb6102f9471032c92ed08/frontend/dockerfile-fe
node:lts,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/alanbarcelos1998/zipin_form/blob/3799ef6145a939bcee88f71eb1f79381fc9fda8d/Dockerfile
node:lts-bullseye AS inode,rm -rf /bin/ls,,https://github.com/TarsCloud/K8SFramework/blob/2632089515f38723334d537aef73d87fdc5d5a7c/compiler/base-compiler-bullseye.Dockerfile
node:lts-buster,apt-get update && apt-get install -y ffmpeg imagemagick webp && apt-get upgrade -y && npm i pm2 -g && rm -rf /var/lib/apt/lists/*,,https://github.com/caseyweb/QUEEN-CHARITY/blob/7bf13e13d86b5da471fb0623b7583284d20a9961/lib/Dockerfile
node:lts,npm install --silent,"WORKDIR /usr/src/app
COPY [""package.json"", ""package-lock.json"", ""./""]",https://github.com/ananthanir/DOSA/blob/5f3ffe71cb9385c77454f2a07049b3806320feaa/ui/Dockerfile
node:lts AS build,npm install,"WORKDIR /app
COPY package*.json ./",https://github.com/danmofo/dmoffat-v3/blob/23762aa122de9400753d9d096ab745befbc6325f/dockerfiles/nginx.dockerfile
node:lts-hydrogen,npm install --omit=dev -y,"COPY ./build /peerprep_matching_service_api/
COPY package.json /peerprep_matching_service_api/
COPY package-lock.json /peerprep_matching_service_api/
WORKDIR /peerprep_matching_service_api",https://github.com/CS3219-AY2324S1-G04/peerprep_matching_service/blob/c90a9af98b1dacf88eafee724d6586c19c0bf389/dockerfiles/api.dockerfile
node:lts,yarn,"WORKDIR /app
COPY . .",https://github.com/ghostdial/ghostdial/blob/5610229690bb7c9a8d6b3db0ecd30cf000bd3bda/Dockerfile-voicemail
node:lts AS builderjs,go mod download,"WORKDIR /app
COPY ../go.mod ../go.sum ./",https://github.com/fordevio/wharf/blob/c5cddcd08f7d06c3ce8bcdb8c6b003f15c2124f8/deployment/Dockerfile
node:lts-gallium,apt update && apt install nano -y,"WORKDIR /app
COPY /frontend/ /app",https://github.com/rvnaras/jenkins-eks-k8s/blob/26d7e480c15c42eb330576c3647d81f4656f17a2/frontend/Dockerfile.fe
node:lts-slim as server,npm ci,"WORKDIR /build
COPY . .",https://github.com/lukaspanni/spotify-stats/blob/1ca4e8303b690a04bc823f25f5789d2677fd5e26/Dockerfile
